sudo: true

services:
- docker

language: python

env:
  global:
  - LANG="C.UTF-8"
  - LC_ALL="C"
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: ng2Wu+1oMndftfY+IpQP2BhfuivnmiL1VvEKpqb/lul1cWrJMTDciXKisXhZclo9IdoVEzwRg49tNMJBMWn+zxWaVR9CHuvOKY0BsFofc6jY6k9KXUreSpQfcvuSOb/Iy0BLZqxPE3qSM/Y94uIMC4yar582TXi+ObP/PdBj+bL/vr8AXd9dm69rXUeKHH1/3unf8FZI0riErGN0EPcWjUIXqxPIM8bAFMG0QLtULGe9qHO9KigLHD/FNPCQK50Z3EPRG4znDbSgcgrT5SpQXW6BUMMTYHQo/sKunR0n/3SkzLuY3ufljpPH/3cNtYvWZ7fMz7zYtpRe12Fr/BAJEk/vgcUmG8eglq18ePIN3Nhfbo0DMLrwDsMGILjk3jBuemKO5NxVlmP+tKcoXN85W0q0kbs8n1VP1hJ/d5+MfTWyLg++OL0D3+jVmQcKb5YVdKAy53ONMFH+hrr3Z+DHJT2jbVaTkS1p9yRjcy+fWe98H7cjFUrEiYS25p88AHWfXt+ltjt1cuvPknQm/PZ6oF8W/nrc+F+QAaJBXp75hXZcn7fboA5wbDlb4PJzbAh3/umNrE7YsEecZJViu/Q843pcm8RXCLhYc1D1k8Y5RCIv8zcwqUgLEyoFmnjHVcpe2J3lINfYxYVga81twtO22WVDqJY4H71gFhpA+Sf7TgY=
  - secure: aL09BA8HrxjC5jj/zp6yYAJPu2QDIry/Nb43nH1xpY7hSiw+pWO0U2RDv/qpKjv1PBaE70EkFIlsZSHzOL6OPdu3wXMBYjmLgp08DTJWLb7aPHgdSy4tguXvKWHuAB92insEZGobRX0jqchnJ3DjfUWA5ZfBKtqEhShbmQNz4ev/H0hahZzurbIdJF+qe+MYol3EcqwZh27thsXETEgta2nqjrH+/Zj5T6+z2T63LIPZOvFuh1xrcA9YMm300oVbKMjSmSu56AIWEQJb7xJzNtkdcu70xOesqWr8NsWbw2B2jsiCnDKfWdcRv/875mY6l8g1AJm7Rbggngiqf1M8lZ+sUvXNkBMO50fz2R+ksfeizC6ORV0gbFb2yObgrNVsbIZw1/7/lltRFh5GqITM0KEalrW7VisXSViD6vin+4PCCh9xHhIQUr4MFiJwGo4/S5JAkiN8zS1/QRixpcx0J4encMCijGxXucD3427ZrxhwkTxstXQXWZv2QckZ5wIUr/qYZcfuZg9zlWxhHA/Nlk+F6eF7p4TEfOsBvgKlCB1NHTAIPMxTUzaDhpG6Jbzh0hwTmwJzHVH7R7fEDEPvvAsqQJyLTIle1S7KyQ/kwti4RlML0GRf5Faref8PRtABM9tZv07yBd8KycWUlN4BoHinNQw/khmY3hGC9Kn9GGw=

install:
- pip install -e "git+https://github.com/avirshup/DockerMake#egg=dockermake"
- pip install -e "git+https://github.com/pyinvoke/invoke#egg=invoke"

script:
- if "$TRAVIS_PULL_REQUEST" = "false" ]; then
    case "$TRAVIS_BRANCH" in
      master|develop)
        echo $DOCKER_PASS | docker login --password-stdin -u $DOCKER_USER docker.io/epcim/salt;
        test -n "$TAG" || TAG="--tag ${TRAVIS_BRANCH/master/latest}";
        PUSH="--push-to-registry -r docker.io/epcim --registry-user $DOCKER_USER --registry-token $DOCKER_PASS";
        docker-make --list | awk '/*/{print $2}'| grep -v '^base\|^common|^layer\|^tini' | xargs -n1 -I% docker-make %  $TAG $CACHE $PUSH;
        ;;
    esac
  else
    docker-make --list | awk '/*/{print $2}'| grep -v '^base\|^common|^layer\|^tini' | xargs -n1 -I% docker-make %  $TAG $CACHE;
  fi;

after_failure:
- test -e dockerfile.fail && cat dockerfile.fail || true

after_success:
- docker images
